Renamed variables that shadowed builtins
CiscoDevNet/python-viptela pull request #95
Opened 2020-11-30 19:46 UTC by ppajersk

Merged if elif statements that contained idenical implementations
Removed identical def code block
Removed unused local variables

2020-12-07 22:13 UTC, jlothian requested changes

2020-12-07 22:13 UTC, jlothian commented on vmanage/api/policy_updates.py
> +            if item1["sequenceName"] == seq_name or seq_name is None:
Not sure you wanted to delete this entire code block?

2020-12-08 01:52 UTC, ppajersk commented on vmanage/api/policy_updates.py
> +            if item1["sequenceName"] == seq_name or seq_name is None:
Its identical to lines 142-146. I also combined the if elif statements on line 135 and 141.

2020-12-08 13:48 UTC, jlothian commented on vmanage/api/policy_updates.py
> +            if item1["sequenceName"] == seq_name or seq_name is None:
Ah got it, missed that bit.

2020-12-08 22:09 UTC, ppajersk commented on vmanage/api/policy_updates.py
> +            if item1["sequenceName"] == seq_name or seq_name is None:
Should I resolve this conversation.

2021-02-23 22:55 UTC, jasonking3 approved these changes
LGTM

2021-02-23 22:57 UTC, merged